{% set version = "1.0.1" %}

package:
  name: escapism
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/e/escapism/escapism-{{ version }}.tar.gz
  sha256: 73256bdfb4f22230f0428fc6efecee61cdc4fad531b6f98b849cb9c80711e4ec

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - escapism
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/minrk/escapism
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Simple, generic API for escaping strings

extra:
  recipe-maintainers:
    - ocefpaf
